<?xml version="1.0" ?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">
  <xacro:include
    filename="$(find robotnik_description)/urdf/wheels/wheel.gazebo.xacro" />
  <xacro:include
    filename="$(find robotnik_description)/urdf/wheels/rubber_wheel/fiqus_agrimate_wheel_back.urdf.xacro" />

  <xacro:property
    name="wheel_big_radius"
    value="0.29" />
  <xacro:property
    name="wheel_width"
    value="0.1375" />
  <xacro:property
    name="wheel_mass"
    value="12.8" />

  <xacro:macro
    name="wheel_rbfiqus_agrimate_back"
    params="prefix parent *origin reflect hq left">
    <xacro:macro
      name="cylinder_inertia"
      params="m r h">
      <inertia
        ixx="${m*(3*r*r+h*h)/12}"
        ixy="0"
        ixz="0"
        iyy="${m*(3*r*r+h*h)/12}"
        iyz="0"
        izz="${m*r*r/2}" />
    </xacro:macro>

    <xacro:property
      name="steering_support_mass"
      value="37.5" />
    <xacro:property
      name="steering_support_width"
      value="0.1" />

    <xacro:property
      name="steer_joint_damping"
      value="1.0" />
    <xacro:property
      name="steer_joint_friction"
      value="1.0" />
    <xacro:property
      name="steer_joint_effort_limit"
      value="200.0" />
    <xacro:property
      name="steer_joint_velocity_limit"
      value="100.0" />

    <joint name="${prefix}steering_joint" type="prismatic">
      <parent link="${parent}" />
      <child link="${prefix}base_wheel" />
      <xacro:insert_block name="origin" />
      <axis xyz="0 0 1" />
      <limit effort="100.0" lower="-0.05" upper="0.0" velocity="1.0"/>
      <dynamics damping="100.0" friction="0.0" spring_reference="0.0" spring_stiffness="5000.0"/>
    </joint>

    <link name="${prefix}base_wheel">
      <visual>
        <xacro:if value="${hq}">
          <xacro:if value="${reflect}">
            <origin
              xyz="0 0 0.0"
              rpy="0 0 0" />
          </xacro:if>
          <xacro:unless value="${reflect}">
            <origin
              xyz="0 0 0.0"
              rpy="0 0 ${pi}" />
          </xacro:unless>
          <geometry>
            <xacro:if value="${left}">
              <mesh
                filename="package://robotnik_description/meshes/bases/rbfiqus/agrimate/Brazo_Agrimate_1.STL" />
            </xacro:if>
            <xacro:unless value="${left}">
              <mesh
                filename="package://robotnik_description/meshes/bases/rbfiqus/agrimate/Brazo_Agrimate_2.STL" />
            </xacro:unless>
          </geometry>
        </xacro:if>

        <xacro:unless value="${hq}">
          <xacro:if value="${reflect}">
            <origin
              xyz="0 0 0.0"
              rpy="0 0 0" />
          </xacro:if>
          <xacro:unless value="${reflect}">
            <origin
              xyz="0 0 0.0"
              rpy="0 0 ${pi}" />
          </xacro:unless>
          <geometry>
            <xacro:if value="${left}">
              <mesh
                filename="package://robotnik_description/meshes/bases/rbfiqus/agrimate/Brazo_Agrimate_1.STL" />
            </xacro:if>
            <xacro:unless value="${left}">
              <mesh
                filename="package://robotnik_description/meshes/bases/rbfiqus/agrimate/Brazo_Agrimate_2.STL" />
            </xacro:unless>
          </geometry>
        </xacro:unless>

        <material name="red">
          <color rgba="0.9 0.1 0.1 1" />
        </material>
      </visual>

      <collision>
        <xacro:if value="${reflect}">
          <origin
            xyz="0 0 0.0"
            rpy="0 0 0" />
        </xacro:if>
        <xacro:unless value="${reflect}">
          <origin
            xyz="0 0 0.0"
            rpy="0 0 ${pi}" />
        </xacro:unless>
        <geometry>
          <xacro:if value="${left}">
              <mesh
                filename="package://robotnik_description/meshes/bases/rbfiqus/agrimate/Brazo_Agrimate_1.STL" />
            </xacro:if>
            <xacro:unless value="${left}">
              <mesh
                filename="package://robotnik_description/meshes/bases/rbfiqus/agrimate/Brazo_Agrimate_2.STL" />
            </xacro:unless>
        </geometry>
      </collision>

      <inertial>
        <mass value="${steering_support_mass}" />
        <xacro:if value="${reflect}">
          <origin
            xyz="0 0 ${wheel_big_radius/1.5}"
            rpy="${pi/2.0} ${pi/2.0} 0" />
        </xacro:if>
        <xacro:unless value="${reflect}">
          <origin
            xyz="0 0 ${wheel_big_radius/1.5}"
            rpy="${pi/2.0} ${pi/2.0} ${pi/2.0}" />
        </xacro:unless>
        <xacro:cylinder_inertia
          m="${steering_support_mass}"
          r="${wheel_big_radius}"
          h="${steering_support_width}" />
      </inertial>
    </link>

    <xacro:gazebo_steering_frame_physics
      name="${prefix}base_wheel" />

    <xacro:fiqus_agrimate_wheel_back
      prefix="${prefix}"
      parent="${prefix}base_wheel"
      reflect="${reflect}"
      hq="${hq}"
      rubber_big_wheel_radius="${wheel_big_radius}"
      rubber_wheel_width="${wheel_width}"
      rubber_wheel_mass="${wheel_mass}">
      <xacro:if value="${left}">
            <origin
              xyz="0 0.18044 0"
              rpy="0 0 0" />
      </xacro:if>
      <xacro:unless value="${left}">
            <origin
              xyz="0 -0.18044 0"
              rpy="0 0 0" />
      </xacro:unless>
    </xacro:fiqus_agrimate_wheel_back>
  </xacro:macro>
</robot>