<?xml version="1.0" ?>
<robot
  name="sensor_intel_realsense_d455"
  xmlns:xacro="http://wiki.ros.org/xacro">
  <xacro:include
    filename="$(find robotnik_sensors)/urdf/depth/depth_camera_plugin.urdf.xacro" />
  <xacro:include
    filename="$(find robotnik_sensors)/urdf/depth/irred_camera_plugin.urdf.xacro" />
  <xacro:include
    filename="$(find robotnik_sensors)/urdf/camera/camera_plugin.urdf.xacro" />
  <xacro:include
    filename="$(find robotnik_sensors)/urdf/imu/imu_plugin.urdf.xacro" />

  <xacro:macro
    name="sensor_intel_realsense_d455"
    params="frame_prefix
            parent
            *origin
            gazebo_ignition:=false
            node_name:=realsense_d455
            node_namespace:=${None}
            topic_prefix:=~/">
    <!-- node_namespace is used from node_name if not set -->
    <xacro:if value="${node_namespace == None}">
      <xacro:property
        name="node_namespace"
        value="${node_name}" />
    </xacro:if>

    <!-- The following values are approximate, and the camera node
     publishing TF values with actual calibrated camera extrinsic values -->
    <xacro:property
      name="d455_cam_depth_to_infra1_offset"
      value="0.0" />
    <xacro:property
      name="d455_cam_depth_to_infra2_offset"
      value="-0.095" />
    <xacro:property
      name="d455_cam_depth_to_color_offset"
      value="-0.059" />

    <!-- The following values model the aluminum peripherial case for the
  	d455 camera, with the camera joint represented by the actual
  	peripherial camera tripod mount -->
    <xacro:property
      name="d455_cam_width"
      value="0.124" />
    <xacro:property
      name="d455_cam_height"
      value="0.029" />
    <xacro:property
      name="d455_cam_depth"
      value="0.026" />
    <xacro:property
      name="d455_cam_mount_from_center_offset"
      value="0.0158" />
    <!-- glass cover is 0.1 mm inwards from front aluminium plate -->
    <xacro:property
      name="d455_glass_to_front"
      value="0.1e-3" />
    <!-- see datasheet Revision 009, Fig. 4-4 page 68 -->
    <xacro:property
      name="d455_zero_depth_to_glass"
      value="4.55e-3" />
    <!-- convenience precomputation to avoid clutter-->
    <xacro:property
      name="d455_mesh_x_offset"
      value="${d455_cam_mount_from_center_offset-d455_glass_to_front-d455_zero_depth_to_glass}" />

    <!-- The following offset is relative to the physical d455 camera peripherial
  	camera tripod mount -->
    <xacro:property
      name="d455_cam_depth_px"
      value="${d455_cam_mount_from_center_offset}" />
    <xacro:property
      name="d455_cam_depth_py"
      value="0.0475" />
    <xacro:property
      name="d455_cam_depth_pz"
      value="${d455_cam_height/2}" />

    <joint
      name="${frame_prefix}base_joint"
      type="fixed">
      <xacro:insert_block name="origin" />
      <parent link="${parent}" />
      <child link="${frame_prefix}base_link" />
    </joint>
    <link name="${frame_prefix}base_link" />

    <!-- camera body, with origin at bottom screw mount -->
    <joint
      name="${frame_prefix}joint"
      type="fixed">
      <parent link="${frame_prefix}base_link" />
      <origin
        xyz="${d455_mesh_x_offset} ${d455_cam_depth_py} ${d455_cam_depth_pz}"
        rpy="0 0 0" />
      <child link="${frame_prefix}link" />
    </joint>
    <link name="${frame_prefix}link">
      <!-- camera link is aligned with the infrared sensor 1 that is "in the middle of the camera", not the one in the edge -->
      <visual>
        <origin
          xyz="${d455_zero_depth_to_glass + d455_glass_to_front} ${-d455_cam_depth_py} 0"
          rpy="${radians(90)} 0 ${radians(90)}" />
        <geometry>
          <mesh
            filename="package://robotnik_sensors/meshes/depth/intel_realsense_d455/intel_d455.stl"
            scale="0.001 0.001 0.001" />
        </geometry>
      </visual>
      <collision>
        <origin
          xyz="${d455_zero_depth_to_glass-d455_cam_depth/2} ${-d455_cam_depth_py} 0"
          rpy="0 0 0" />
        <geometry>
          <box
            size="${d455_cam_depth} ${d455_cam_width} ${d455_cam_height}" />
        </geometry>
      </collision>
      <inertial>
        <origin
          xyz="0 0 0"
          rpy="0 0 0" />
        <mass value="0.072" />
        <inertia
          ixx="0.003881243"
          ixy="0.0"
          ixz="0.0"
          iyy="0.000498940"
          iyz="0.0"
          izz="0.003879257" />
        <!-- <xacro:solid_cuboid_inertia
          m="0.1"
          w="0.025"
          h="0.09"
          d="0.025" /> -->
      </inertial>
    </link>

    <!-- Use the nominal extrinsics between camera frames if the calibrated extrinsics aren't being published. e.g. running the device in simulation  -->
    <!-- camera depth joints and links -->
    <joint
      name="${frame_prefix}depth_joint"
      type="fixed">
      <origin
        xyz="0 0 0"
        rpy="0 0 0" />
      <parent link="${frame_prefix}link" />
      <child link="${frame_prefix}depth_frame" />
    </joint>
    <link name="${frame_prefix}depth_frame" />

    <joint
      name="${frame_prefix}depth_optical_joint"
      type="fixed">
      <origin
        xyz="0 0 0"
        rpy="${-radians(90)} 0 ${-radians(90)}" />
      <parent link="${frame_prefix}depth_frame" />
      <child link="${frame_prefix}depth_optical_frame" />
    </joint>
    <link name="${frame_prefix}depth_optical_frame" />

    <!-- camera left IR joints and links -->
    <joint
      name="${frame_prefix}infra1_joint"
      type="fixed">
      <origin
        xyz="0 ${d455_cam_depth_to_infra1_offset} 0"
        rpy="0 0 0" />
      <parent link="${frame_prefix}link" />
      <child link="${frame_prefix}infra1_frame" />
    </joint>
    <link name="${frame_prefix}infra1_frame" />

    <joint
      name="${frame_prefix}infra1_optical_joint"
      type="fixed">
      <origin
        xyz="0 0 0"
        rpy="${-radians(90)} 0 ${-radians(90)}" />
      <parent link="${frame_prefix}infra1_frame" />
      <child link="${frame_prefix}infra1_optical_frame" />
    </joint>
    <link name="${frame_prefix}infra1_optical_frame" />

    <!-- camera right IR joints and links -->
    <joint
      name="${frame_prefix}infra2_joint"
      type="fixed">
      <origin
        xyz="0 ${d455_cam_depth_to_infra2_offset} 0"
        rpy="0 0 0" />
      <parent link="${frame_prefix}link" />
      <child link="${frame_prefix}infra2_frame" />
    </joint>
    <link name="${frame_prefix}infra2_frame" />

    <joint
      name="${frame_prefix}infra2_optical_joint"
      type="fixed">
      <origin
        xyz="0 0 0"
        rpy="${-radians(90)} 0 ${-radians(90)}" />
      <parent link="${frame_prefix}infra2_frame" />
      <child link="${frame_prefix}infra2_optical_frame" />
    </joint>
    <link name="${frame_prefix}infra2_optical_frame" />

    <!-- camera color joints and links -->
    <joint
      name="${frame_prefix}color_joint"
      type="fixed">
      <origin
        xyz="0 ${d455_cam_depth_to_color_offset} 0"
        rpy="0 0 0" />
      <parent link="${frame_prefix}link" />
      <child link="${frame_prefix}color_frame" />
    </joint>
    <link name="${frame_prefix}color_frame" />

    <joint
      name="${frame_prefix}color_optical_joint"
      type="fixed">
      <origin
        xyz="0 0 0"
        rpy="${-radians(90)} 0 ${-radians(90)}" />
      <parent link="${frame_prefix}color_frame" />
      <child link="${frame_prefix}color_optical_frame" />
    </joint>
    <link name="${frame_prefix}color_optical_frame" />

    <!-- IMU -->
    <!-- see datasheet Revision 009, page 114 -->
    <xacro:property
      name="d455_imu_px"
      value="-0.01602" />
    <xacro:property
      name="d455_imu_py"
      value="-0.03022" />
    <xacro:property
      name="d455_imu_pz"
      value="0.0074" />

    <joint
      name="${frame_prefix}accel_joint"
      type="fixed">
      <origin
        xyz="${d455_imu_px} ${d455_imu_py} ${d455_imu_pz}"
        rpy="0 0 0" />
      <parent link="${frame_prefix}link" />
      <child link="${frame_prefix}accel_frame" />
    </joint>
    <link name="${frame_prefix}accel_frame" />

    <joint
      name="${frame_prefix}accel_optical_joint"
      type="fixed">
      <origin
        xyz="0 0 0"
        rpy="${-radians(90)} 0 ${-radians(90)}" />
      <parent link="${frame_prefix}accel_frame" />
      <child link="${frame_prefix}accel_optical_frame" />
    </joint>
    <link name="${frame_prefix}accel_optical_frame" />

    <joint
      name="${frame_prefix}gyro_joint"
      type="fixed">
      <origin
        xyz="${d455_imu_px} ${d455_imu_py} ${d455_imu_pz}"
        rpy="0 0 0" />
      <parent link="${frame_prefix}link" />
      <child link="${frame_prefix}gyro_frame" />
    </joint>
    <link name="${frame_prefix}gyro_frame" />

    <joint
      name="${frame_prefix}gyro_optical_joint"
      type="fixed">
      <origin
        xyz="0 0 0"
        rpy="${-radians(90)} 0 ${-radians(90)}" />
      <parent link="${frame_prefix}gyro_frame" />
      <child link="${frame_prefix}gyro_optical_frame" />
    </joint>
    <link name="${frame_prefix}gyro_optical_frame" />

    <joint
      name="${frame_prefix}imu_optical_joint"
      type="fixed">
      <origin
        xyz="0 0 0"
        rpy="0 0 0" />
      <parent link="${frame_prefix}gyro_optical_frame" />
      <child link="${frame_prefix}imu_optical_frame" />
    </joint>
    <link name="${frame_prefix}imu_optical_frame" />

    <xacro:camera_plugin
      node_namespace="${node_namespace}"
      node_name="${node_name}_color"
      topic_prefix="${topic_prefix}_color"
      gazebo_ignition="${gazebo_ignition}"
      optical_frame="${frame_prefix}color_optical_frame"
      reference_frame="${frame_prefix}color_frame"
      horizontal_fov="90.0"
      vertical_fov="65.0"
      video_width="1280"
      video_height="800"
      min_depth="0.18"
      max_depth="100"
      rate="30" />

    <xacro:irred_camera_plugin
      node_namespace="${node_namespace}"
      node_name="${node_name}_irred1"
      topic_prefix="${topic_prefix}_irred1"
      gazebo_ignition="${gazebo_ignition}"
      optical_frame="${frame_prefix}infra1_optical_frame"
      reference_frame="${frame_prefix}infra1_frame"
      horizontal_fov="90"
      vertical_fov="62"
      video_width="1280"
      video_height="720"
      min_depth="0.18"
      max_depth="100"
      rate="30" />

    <xacro:irred_camera_plugin
      node_namespace="${node_namespace}"
      node_name="${node_name}_irred2"
      topic_prefix="${topic_prefix}_irred2"
      gazebo_ignition="${gazebo_ignition}"
      optical_frame="${frame_prefix}infra2_optical_frame"
      reference_frame="${frame_prefix}infra2_frame"
      horizontal_fov="90"
      vertical_fov="62"
      video_width="1280"
      video_height="720"
      min_depth="0.18"
      max_depth="100"
      rate="30" />

    <xacro:depth_camera_plugin
      node_namespace="${node_namespace}"
      node_name="${node_name}_depth"
      topic_prefix="${topic_prefix}_depth"
      gazebo_ignition="${gazebo_ignition}"
      optical_frame="${frame_prefix}depth_optical_frame"
      reference_frame="${frame_prefix}depth_frame"
      horizontal_fov="87"
      vertical_fov="58"
      video_width="1280"
      video_height="720"
      min_depth="0.18"
      max_depth="100"
      rate="30" />

    <xacro:imu_plugin
      node_namespace="${node_namespace}"
      node_name="${node_name}"
      gazebo_ignition="${gazebo_ignition}"
      frame_link="${frame_prefix}link"
      rate="200.0" />
  </xacro:macro>
</robot>
